Feat: add order model
OmarQaqish/cook-link pull request #39
Opened 2023-07-07 14:31 UTC by OmarQaqish

Order model: Issue #8 

- [ ] Created the order model.
- [ ] Added a function to calculate the total price of the order automatically.

2023-07-07 14:54 UTC, aydinfz requested changes
Thanks for your work, could you please export models?

2023-07-07 14:58 UTC, OmarQaqish commented
> Thanks for your work, could you please export models?

Oh, woops, forgot to do that. I will do that now

2023-07-07 15:09 UTC, aydinfz approved these changes

2023-07-08 13:58 UTC, tarik310 approved these changes

2023-07-09 08:27 UTC, merged